@extends('layouts.app')

@section('content')
<x-common.page-breadcrumb pageTitle="Edit Tim Asesor Program" />
<form method="POST" action="{{ route('admin.assessor-assignments.update', $program) }}" class="space-y-6" x-data="{ selected: @js(array_map('intval', old('assessor_ids', $selectedAssessors))), all: @js($assessors->pluck('id')->map(fn ($id) => (int) $id)->values()->all()), assessorValidationOpen: @js($errors->has('assessor_ids')) }" @submit="if (selected.length === 0) { $event.preventDefault(); assessorValidationOpen = true }">@csrf @method('PUT')
    <div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-lg font-semibold text-gray-800 dark:text-white/90">{{ $program->name }}</h1><p class="mt-1 text-sm text-gray-500">Tim ini diterapkan ke seluruh {{ $program->simulations->count() }} simulasi dalam program.</p></div><span class="w-fit rounded-full bg-brand-50 px-3 py-1 text-xs font-medium text-brand-600 dark:bg-brand-500/10 dark:text-brand-400"><span x-text="selected.length"></span> asesor dipilih</span></div></div>
    <section class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><div class="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-semibold text-gray-800 dark:text-white/90">Tim Asesor Program</h2><p class="mt-1 text-sm text-gray-500">Asesor terpilih mendapatkan akses ke seluruh simulasi program.</p></div>@if($assessors->isNotEmpty())<label class="flex cursor-pointer items-center gap-2 rounded-lg bg-gray-50 px-3 py-2 text-sm font-medium text-gray-700 dark:bg-white/5 dark:text-gray-300"><input type="checkbox" :checked="selected.length === all.length" @change="selected = $event.target.checked ? [...all] : []" class="size-4 rounded border-gray-300 text-brand-500 focus:ring-brand-500">Pilih semua asesor</label>@endif</div>
        <div class="grid max-h-[420px] grid-cols-1 gap-2 overflow-y-auto md:grid-cols-2 xl:grid-cols-3">@forelse($assessors as $assessor)<label class="flex cursor-pointer items-center gap-3 rounded-xl border border-gray-200 p-3 hover:bg-gray-50 dark:border-gray-800 dark:hover:bg-white/5"><input type="checkbox" name="assessor_ids[]" value="{{ $assessor->id }}" x-model.number="selected" class="size-4 rounded border-gray-300 text-brand-500 focus:ring-brand-500"><span class="min-w-0"><span class="block truncate text-sm font-medium text-gray-800 dark:text-white/90">{{ $assessor->name }}</span><span class="block truncate text-xs text-gray-500">{{ $assessor->email }}</span></span></label>@empty<p class="text-sm text-gray-500">Belum ada akun asesor. Buat akun asesor melalui Super Admin.</p>@endforelse</div>
    </section>
    <div class="flex flex-wrap justify-end gap-3"><a href="{{ route('admin.assessor-assignments.index') }}" class="crud-btn-secondary">Batal</a><button class="crud-btn-primary">Terapkan ke Semua Simulasi</button></div>
    <div x-show="assessorValidationOpen" x-cloak @keydown.escape.window="assessorValidationOpen = false" class="fixed inset-0 z-99999 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="team-validation-title"><div class="absolute inset-0 bg-gray-900/50 backdrop-blur-sm" @click="assessorValidationOpen = false"></div><div x-show="assessorValidationOpen" x-transition class="relative w-full max-w-md rounded-2xl bg-white p-6 text-center shadow-theme-xl dark:bg-gray-900"><div class="mx-auto flex size-12 items-center justify-center rounded-full bg-error-50 text-error-500 dark:bg-error-500/10"><svg class="size-6" viewBox="0 0 24 24" fill="none"><path d="M12 8v5m0 3.5v.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg></div><h3 id="team-validation-title" class="mt-4 text-lg font-semibold text-gray-800 dark:text-white/90">Tim Asesor Tidak Boleh Kosong</h3><p class="mt-2 text-sm text-gray-500 dark:text-gray-400">Pilih minimal satu asesor sebelum menerapkan tim ke seluruh simulasi.</p><button type="button" @click="assessorValidationOpen = false" class="crud-btn-primary mt-6 w-full">Kembali Pilih Asesor</button></div></div>
</form>
@endsection
