@extends('layouts.app')
@section('content')
<x-common.page-breadcrumb pageTitle="Peserta Simulasi" />
<div class="rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]">
<div class="border-b border-gray-200 px-5 py-4 dark:border-gray-800"><span class="text-xs font-medium uppercase text-brand-500">Simulasi {{ $programSimulation->scenario->type->sequence }}</span><h2 class="mt-1 font-semibold text-gray-800 dark:text-white/90">{{ $programSimulation->scenario->type->name }}</h2><p class="mt-1 text-sm text-gray-500">{{ $programSimulation->program->name }}</p></div>
<div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 dark:divide-gray-800"><thead class="bg-gray-50 dark:bg-gray-900/50"><tr>@foreach(['Peserta','Status','Dikumpulkan','File/Jawaban'] as $heading)<th class="px-5 py-3 text-left text-xs font-medium uppercase text-gray-500">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">
@if($programSimulation->scenario->type->delivery_mode === 'assessor_observation')
@forelse($programSimulation->program->participants as $participant) @php($session = $programSimulation->sessions->firstWhere('assessment_participant_id', $participant->id))
<tr><td class="px-5 py-4"><div class="text-sm font-medium text-gray-800 dark:text-white/90">{{ $participant->user->name }}</div><div class="text-xs text-gray-500">{{ $participant->user->email }}</div></td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $session?->status === 'submitted' ? 'Simulasi 2 selesai' : ($session?->status === 'in_progress' ? 'Sedang berlangsung' : 'Belum dimulai') }}</td><td class="px-5 py-4 text-sm text-gray-500">{{ $session?->submitted_at?->format('d M Y H:i') ?? '-' }}</td><td class="px-5 py-4">@if($session?->status === 'submitted')<a href="{{ route('asesor.reviews.edit', $session) }}" class="text-sm font-medium text-success-600">Beri penilaian →</a>@else<span class="text-xs text-gray-400">Menunggu peserta mengumpulkan</span>@endif</td></tr>
@empty <tr><td colspan="4" class="px-5 py-12 text-center text-sm text-gray-500">Belum ada peserta pada program ini.</td></tr> @endforelse
@else
@forelse($programSimulation->sessions as $session) @php($submission = $session->submissions->sortByDesc('revision')->first())
<tr><td class="px-5 py-4"><div class="text-sm font-medium text-gray-800 dark:text-white/90">{{ $session->participant->user->name }}</div><div class="text-xs text-gray-500">{{ $session->participant->user->email }}</div></td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ str_replace('_', ' ', $session->status) }}</td><td class="px-5 py-4 text-sm text-gray-500">{{ $session->submitted_at?->format('d M Y H:i') ?? '-' }}</td><td class="px-5 py-4"><div class="flex flex-col items-start gap-1">@if($submission?->storage_path)<span class="text-xs text-gray-500">{{ $submission->original_filename }}</span><div class="flex flex-wrap gap-3"><a target="_blank" href="{{ route('asesor.submissions.preview', $submission) }}" class="text-sm font-medium text-brand-500">Preview fullscreen</a><a href="{{ route('asesor.submissions.download', $submission) }}" class="text-sm font-medium text-gray-500">Unduh PDF</a></div>@elseif($submission)<span class="text-sm text-gray-500">Jawaban tersimpan</span>@else<span class="text-sm text-gray-400">Belum ada</span>@endif @if($session->status === 'submitted')<a href="{{ route('asesor.reviews.edit', $session) }}" class="text-sm font-medium text-success-600">Beri penilaian →</a>@endif</div></td></tr>
@empty <tr><td colspan="4" class="px-5 py-12 text-center text-sm text-gray-500">Belum ada peserta yang memulai simulasi.</td></tr> @endforelse
@endif
</tbody></table></div></div>
@endsection
