@extends('layouts.app')
@section('content')
<x-common.page-breadcrumb pageTitle="Peserta Assessment" />
@if(session('success'))<div class="mb-5 rounded-lg border border-success-200 bg-success-50 px-4 py-3 text-sm text-success-700">{{ session('success') }}</div>@endif
@if(session('error'))<div class="mb-5 rounded-lg border border-error-200 bg-error-50 px-4 py-3 text-sm text-error-700 dark:border-error-500/30 dark:bg-error-500/10 dark:text-error-400">{{ session('error') }}</div>@endif
<div x-data="{ deleting: null }" class="rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]">
    <div class="flex flex-col gap-4 border-b border-gray-200 px-5 py-4 sm:flex-row sm:items-center sm:justify-between dark:border-gray-800"><div><h2 class="font-semibold text-gray-800 dark:text-white/90">Akun Peserta Assessment</h2><p class="mt-1 text-sm text-gray-500">Akun peserta yang dapat ditempatkan ke program assessment.</p></div><a href="{{ route('admin.participants.create') }}" class="crud-btn-primary shrink-0">Tambah Peserta</a></div>
    <div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 dark:divide-gray-800"><thead class="bg-gray-50 dark:bg-gray-900/50"><tr>@foreach(['Peserta','Program Diikuti','Dibuat','Aksi'] as $heading)<th class="px-5 py-3 text-left text-xs font-medium uppercase text-gray-500">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@forelse($participants as $participant)<tr class="transition-colors hover:bg-gray-50/70 dark:hover:bg-white/[0.02]"><td class="px-5 py-4"><div class="text-sm font-medium text-gray-800 dark:text-white/90">{{ $participant->name }}</div><div class="text-xs text-gray-500">{{ $participant->email }}</div></td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $participant->assessment_participations_count }}</td><td class="px-5 py-4 text-sm text-gray-500">{{ $participant->created_at->format('d M Y') }}</td><td class="px-5 py-4"><div class="crud-actions"><a href="{{ route('admin.participants.edit', $participant) }}" class="crud-btn-soft-neutral">Edit</a><button type="button" @click="deleting = { name: @js($participant->name), action: @js(route('admin.participants.destroy', $participant)) }" class="crud-btn-soft-danger">Hapus</button></div></td></tr>@empty<tr><td colspan="4" class="px-5 py-12 text-center text-sm text-gray-500">Belum ada akun peserta.</td></tr>@endforelse</tbody></table></div>
    @if($participants->hasPages())<div class="border-t border-gray-200 px-5 py-4 dark:border-gray-800">{{ $participants->links() }}</div>@endif
    <div x-show="deleting" x-cloak @keydown.escape.window="deleting = null" class="fixed inset-0 z-99999 flex items-center justify-center p-4"><div class="absolute inset-0 bg-gray-900/50 backdrop-blur-sm" @click="deleting = null"></div><div x-show="deleting" x-transition class="relative w-full max-w-md rounded-2xl bg-white p-6 shadow-theme-xl dark:bg-gray-900"><h3 class="text-lg font-semibold text-gray-800 dark:text-white/90">Hapus Peserta Assessment?</h3><p class="mt-2 text-sm text-gray-500 dark:text-gray-400">Akun <span class="font-medium text-gray-700 dark:text-gray-300" x-text="deleting?.name"></span> akan dihapus permanen. Peserta yang sudah masuk ke program tidak dapat dihapus.</p><div class="mt-6 flex flex-wrap justify-end gap-3"><button type="button" @click="deleting = null" class="crud-btn-secondary">Batal</button><form method="POST" :action="deleting?.action"><input type="hidden" name="_token" value="{{ csrf_token() }}"><input type="hidden" name="_method" value="DELETE"><button class="crud-btn-danger">Ya, Hapus</button></form></div></div></div>
</div>
@endsection
